GET http://localhost:3000/products
###
GET http://localhost:3000/products/65d49003fb44d05f2907c121
###
POST http://localhost:3000/products
Content-Type: application/json

{
			"id": 1,
			"code": "595959",
			"name": "Bamboo Watch",
			"description": "Product Description",
			"image": "bamboo-watch.jpg",
			"price": 65,
			"category": "Accessories",
			"quantity": 24,
			"inventoryStatus": "INSTOCK",
			"rating": 5
}

###
POST http://localhost:3000/products/multiple
Content-Type: application/json

[
	{
			"id":10,
			"code": "123",
			"name": "Banana multiple 1",
			"description": "Product Description",
			"image": "bamboo-watch.jpg",
			"price": 65,
			"category": "Accessories",
			"quantity": 24,
			"inventoryStatus": "INSTOCK",
			"rating": 5
	},
	{
			"id":11,
			"code": "454",
			"name": "Banana multiple 2",
			"description": "Product Description",
			"image": "bamboo-watch.jpg",
			"price": 65,
			"category": "Accessories",
			"quantity": 14,
			"inventoryStatus": "INSTOCK",
			"rating": 5
	}
]
###

DELETE http://localhost:3000/products/65d4be49514150488b4b4e3d

###

PATCH http://localhost:3000/products/65d4bfd1514150488b4b4e43
Content-Type: application/json

{
			"quantity": 107
}